<a href="https://colab.research.google.com/github/situser-testing/grocerystore/blob/main/Lab01_Student_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lab01 ICT2506C Lab: Introduction to Pandas

There are three main data structures in Pandas: Series, Index and DataFrame. However the most common ones are DataFrame and Series. Hence for this course we will only go through these two data structures. By the end of the lab, you would have learnt the following:

1.1 How to create pandas objects from python list and python dictionary.

1.2. How to create pandas dataframe objects from python list, python dictionary and csv files.

1.3 How to index / slice pandas series and dataframes.

We will first import the necessary libraries. Please import the pandas library as pd.

### Section 1.1 Pandas Series Object

A Pandas **Series** is a one-dimensional array, very similar to that of a list, or a numpy array. The main difference is the indexes of the Series object need not be numerical indexes, but can be created from another list or array. We illustrate this below:

#### Section 1.1.1 Create Series from List

In [ ]:
temp_list = [1, 2, 3, 4, 5]

Create a pandas series called temp_series from temp_list.

In [ ]:
print(temp_series)
print(temp_series.values)
print(temp_series.index)

0    1
1    2
2    3
3    4
4    5
dtype: int64
[1 2 3 4 5]
RangeIndex(start=0, stop=5, step=1)


Print out the value of the series at index 0.

1

Print out the value of the series from index 2 to the end of the series.

2    3
3    4
4    5
dtype: int64

Print out the value of the series from index 2 to index 3 (both inclusive) of the series.

2    3
3    4
dtype: int64

Print out the value of the series from index -3 (inclusive) to index -1 (not inclusive) of the series.

2    3
3    4
dtype: int64

Do note that unlike a typical python list, negative indexing does not work for a series, and you need the colon character.

4    5
dtype: int64

#### Section 1.1.2 Create Series from List where indices are another List

In [ ]:
temp_list = [0, 1, 2, 3, 4, 5]
index_list = ['a', 'b', 'c', 'd', 'e', 'f']

Create a series known as temp_series with values of temp_list and indexes of index_list.

In [ ]:
print(temp_series)
print(temp_series.values)
print(temp_series.index)

a    0
b    1
c    2
d    3
e    4
f    5
dtype: int64
[0 1 2 3 4 5]
Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')


We can access the individual values now through their indices. Please access the value with the index value 'd'.

3

Do note that these indices can take any value that we wish to give them. We can give them indices such as:

In [ ]:
temp_series = pd.Series([0, 1, 2, 3, 4, 5],
                 index=['8046352B', '8573645H', '9729384G', '1583726D', '2093837C', '239485723E'])

In [ ]:
print(temp_series)
print(temp_series.values)
print(temp_series.index)

8046352B      0
8573645H      1
9729384G      2
1583726D      3
2093837C      4
239485723E    5
dtype: int64
[0 1 2 3 4 5]
Index(['8046352B', '8573645H', '9729384G', '1583726D', '2093837C',
       '239485723E'],
      dtype='object')


#### Section 1.1.3 Create Series from Dictionary

In [ ]:
electorate_dict = {'Aljunied': 150303,
                   'Ang Mo Kio': 180186,
                   'Bishan': 100036,
                   'Chua Chu Kang': 103231,
                   'East Coast': 120239}

Create a series from the dictionary and print out the resulting series.

Aljunied         150303
Ang Mo Kio       180186
Bishan           100036
Chua Chu Kang    103231
East Coast       120239
dtype: int64

Print out the number of voters at "Ang Mo Kio".

180186

Print out the voters from "Aljunied" to "East Coast" (both inclusive)

Aljunied         150303
Ang Mo Kio       180186
Bishan           100036
Chua Chu Kang    103231
East Coast       120239
dtype: int64

Note this is a bit confusing. The end index is included!!! (as compared to the list where the end index is not included...! Even at the top, the end index is not included...!)

### Section 1.2 Pandas DataFrame Object

A Pandas **DataFrame** can be considered to be a table, with rows, columns and headers.

#### Section 1.2.1 Create DataFrame from List

In [ ]:
temp_list = ['honda', 'toyota', 'kia', 'bmw', 'mazda']

Create a dataframe called temp_pd and print it out.

0
0   honda
1  toyota
2     kia
3     bmw
4   mazda

If you wish to have the header, you can use the columns keyword. Notice that columns takes a list as the input.

Create a dataframe called temp_pd from temp_list with "car brand" as the columns name. Please ue the columns keyword.

Please print it out.

car brand
0     honda
1    toyota
2       kia
3       bmw
4     mazda

Suppose we have more than one column, every row should be a list.

|car brand|price|
|-|-|
|honda|150000|
etc

Do note that the easier way would be to create the dataframe from a dictionary (see 1.2.2).

In [ ]:
temp_list_0 = ['honda', 150000]
temp_list_1 = ['toyota', 130000]
temp_list_2 = ['kia', 100000]
temp_list_3 = ['bmw', 250000]
temp_list_4 = ['mazda', 140000]

temp_list = [temp_list_0, temp_list_1, temp_list_2,temp_list_3, temp_list_4]

temp_pd = pd.DataFrame(temp_list, columns=["car brand", "price"])
temp_pd

car brand   price
0     honda  150000
1    toyota  130000
2       kia  100000
3       bmw  250000
4     mazda  140000

#### Section 1.2.2 Create DataFrame from Dictionary

In [ ]:
temp_list = ['honda', 'toyota', 'kia', 'bmw', 'mazda']
temp_dict = {"car brand": temp_list}

Create a dataframe called "temp_pd" from temp_dict.

car brand
0     honda
1    toyota
2       kia
3       bmw
4     mazda

If we have more than one column:

In [ ]:
temp_list_0 = ['honda', 'toyota', 'kia', 'bmw', 'mazda']
temp_list_1 = [150000, 130000, 100000, 250000, 140000]

Create a dictionary from temp_list_0 and temp_list_1. After that create a pandas dataframe called temp_pd from this dictionary.

car brand   price
0     honda  150000
1    toyota  130000
2       kia  100000
3       bmw  250000
4     mazda  140000

Print out the columns of the dataframe. You can use the columns keyword or the keys function.

Index(['car brand', 'price'], dtype='object')

['car brand', 'price']

Print out the column "car brand" of the dataframe.

0     honda
1    toyota
2       kia
3       bmw
4     mazda
Name: car brand, dtype: object

#### Section 1.2.3 Create DataFrame from CSV

The most common option you may do is a load DataFrame from csv.

In [ ]:
!wget https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2021-financial-year-provisional/Download-data/annual-enterprise-survey-2021-financial-year-provisional-size-bands-csv.csv

--2024-01-07 14:35:49--  https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2021-financial-year-provisional/Download-data/annual-enterprise-survey-2021-financial-year-provisional-size-bands-csv.csv
Resolving www.stats.govt.nz (www.stats.govt.nz)... 45.60.11.104
Connecting to www.stats.govt.nz (www.stats.govt.nz)|45.60.11.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1492633 (1.4M) [text/csv]
Saving to: ‘annual-enterprise-survey-2021-financial-year-provisional-size-bands-csv.csv’

annual-enterprise-s 100%[===================>]   1.42M  --.-KB/s    in 0.09s   

2024-01-07 14:35:51 (16.4 MB/s) - ‘annual-enterprise-survey-2021-financial-year-provisional-size-bands-csv.csv’ saved [1492633/1492633]



The data has been downloaded into a file known as "annual-enterprise-survey-2021-financial-year-provisional-size-bands-csv.csv".

Please use the read_csv function to read from the file.

In [ ]:
sample_df = pd.read_csv("annual-enterprise-survey-2021-financial-year-provisional-size-bands-csv.csv")

Print out the first five rows with the head function.

year industry_code_ANZSIC               industry_name_ANZSIC rme_size_grp  \
0  2011                    A  Agriculture, Forestry and Fishing          a_0   
1  2011                    A  Agriculture, Forestry and Fishing          a_0   
2  2011                    A  Agriculture, Forestry and Fishing          a_0   
3  2011                    A  Agriculture, Forestry and Fishing          a_0   
4  2011                    A  Agriculture, Forestry and Fishing          a_0   

                                          variable  value               unit  
0                                    Activity unit  46134              COUNT  
1                           Rolling mean employees      0              COUNT  
2                          Salaries and wages paid    279  DOLLARS(millions)  
3  Sales, government funding, grants and subsidies   8187  DOLLARS(millions)  
4                                     Total income   8866  DOLLARS(millions)

### Section 1.3 Pandas DataFrame Indexing / Slicing

Do note that *indexing* refers to columns while *slicing* refers to rows.

#### Section 1.3.1 Default Slicing

Print out the pandas object temp_series.

8046352B      0
8573645H      1
9729384G      2
1583726D      3
2093837C      4
239485723E    5
dtype: int64

Print out the values of the series from "8573645H" to "2093837C" (both inclusive)

8573645H    1
9729384G    2
1583726D    3
2093837C    4
dtype: int64

We now have the following variables.

In [ ]:
temp_list_0 = ['honda', 'toyota', 'kia', 'bmw', 'mazda']
temp_list_1 = [150000, 130000, 100000, 250000, 140000]
temp_indexes = ['c0','c1','c2','c3','c4']

Let's create a dataframe, with column "car brand" with values from temp_list_0 and column "price" with values of temp_list_1 with an explicit index.

car brand   price
c0     honda  150000
c1    toyota  130000
c2       kia  100000
c3       bmw  250000
c4     mazda  140000

Print temp_pd from "c2" to "c4".

car brand   price
c2       kia  100000
c3       bmw  250000
c4     mazda  140000

Print temp_pd from index 2 (inclusive) to index 4 (non inclusive).

car brand   price
c2       kia  100000
c3       bmw  250000

#### Section 1.3.2 Indexing using loc, iloc

Using indexes may sometimes be confusing, especially with integer indexes.

Hence Pandas has two special attributes, loc and iloc. loc allows for slicing referencing to the explicit index while iloc references that to the numerical index.

In [ ]:
temp_pd

car brand   price
c0     honda  150000
c1    toyota  130000
c2       kia  100000
c3       bmw  250000
c4     mazda  140000

Use .loc to slice rows from c1 to c4 (inclusive)

car brand   price
c1    toyota  130000
c2       kia  100000
c3       bmw  250000
c4     mazda  140000

Use .loc to slice rows from c1 to c4 (inclusive) indexing only the "car brand" column

car brand
c1    toyota
c2       kia
c3       bmw
c4     mazda

Use .iloc to slice rows from 1 to 3 (non inclusive)

car brand   price
c1    toyota  130000
c2       kia  100000

Use .iloc to slice rows from 1 to 3 (non inclusive) indexing only the "car brand" column

car brand
c1    toyota
c2       kia